export const FETCH_WEATHER = "COMMAND/FETCH_WEATHER_FOR_LAT_LNG";
export const API_ERROR = "EVENT/API_ERROR_RECEIVED";
export const WEATHER_DATA_RECEIVED = "EVENT/WEATHER_DATA_RECEIVED";
export const WEATHER_ID_RECEIVED = "EVENT/WEATHER_ID_RECEIVED";
export const POLL_START_TEXAS = "COMMAND/POLL_START_TEXAS";
export const POLL_STOP_TEXAS = "COMMAND/POLL_STOP_TEXAS";

export const NEW_TAB_SELECTED = "EVENT/CHANGE_CURRENT_TAB";
export const CHANGE_CHART_DATA = "COMMAND/CHANGE_CHART_DATA";
export const CHANGE_CHART_VISIBILITY = "COMMAND/CHANGE_CHART_VISIBILITY";

export const FETCH_MAP_WEATHER_DATA = "COMMAND/FETCH_MAP_WEATHER_DATA";
export const MAP_WEATHER_DATA_RECEIVED = "EVENT/MAP_WEATHER_DATA_RECIEVED";
export const POLL_START_MAP = "COMMAND/POLL_START_MAP";
export const POLL_STOP_MAP = "COMMAND/POLL_STOP_MAP";
export const CHANGE_MAP_PIN_POINT = "COMMAND/CHANGE_MAP_PIN_POINT";


export const CHANGE_APP_VIEW = "COMMAND/CHANGE_APP_VIEW";
export const INITIALIZE_PIN_POINT = "COMMAND/INITIALIZE_PIN_POINT";
