export const FETCH_WEATHER = "COMMAND/FETCH_WEATHER_FOR_LAT_LNG";
export const API_ERROR = "EVENT/API_ERROR_RECEIVED";
export const WEATHER_DATA_RECEIVED = "EVENT/WEATHER_DATA_RECEIVED";
export const WEATHER_ID_RECEIVED = "EVENT/WEATHER_ID_RECEIVED";
export const POLL_START = "COMMAND/POLL_START";
export const POLL_STOP = "COMMAND/POLL_STOP";

export const NEW_TAB_SELECTED = "EVENT/CHANGE_CURRENT_TAB";
export const CHANGE_CHART_DATA = "COMMAND/CHANGE_CHART_DATA";
export const CHANGE_CHART_VISIBILITY = "COMMAND/CHANGE_CHART_VISIBILITY";
